"""Tests for the psycopg3 shim ``src/repositories/pg.py``.

Covers:
  * ``translate()`` SQLite -> Postgres rewriting, including the string-literal
    safety fix (findings V3 / L4) — ``translate`` previously had ZERO tests
    (finding T1).
  * Undefined-COLUMN errors propagate instead of degrading to an empty result
    (finding H3), while undefined-TABLE still degrades to ``OperationalError``.
  * ``lastrowid`` emulation only probes ``lastval()`` when a row was actually
    inserted, and is SAVEPOINT-safe inside a transaction (findings V2 / H2).
"""

import psycopg
import pytest

from src.repositories import pg


# ----------------------------------------------------------------------------
# translate() — table-driven (finding T1: translate had no tests)
# ----------------------------------------------------------------------------
@pytest.mark.parametrize(
    "sql,expected",
    [
        # normal bind placeholders -> %s
        ("INSERT INTO t(a, b) VALUES(?, ?)", "INSERT INTO t(a, b) VALUES(%s, %s)"),
        ("SELECT * FROM t WHERE id = ?", "SELECT * FROM t WHERE id = %s"),
        # ``?`` INSIDE a string literal is data, not a placeholder (V3/L4)
        (
            "SELECT * FROM t WHERE note = 'ok?' AND id = ?",
            "SELECT * FROM t WHERE note = 'ok?' AND id = %s",
        ),
        # ``rowid`` INSIDE a string literal must survive; the bare token -> ctid
        (
            "SELECT rowid FROM t WHERE note = 'has rowid inside'",
            "SELECT ctid FROM t WHERE note = 'has rowid inside'",
        ),
        (
            "SELECT rowid FROM t WHERE id = ?",
            "SELECT ctid FROM t WHERE id = %s",
        ),
        # '' escaped-quote inside a literal keeps the enclosed ``?`` protected
        ("SELECT 'a''b?' , ? FROM t", "SELECT 'a''b?' , %s FROM t"),
    ],
)
def test_translate_exact(sql, expected):
    assert pg.translate(sql) == expected


def test_translate_insert_or_ignore():
    out = pg.translate("INSERT OR IGNORE INTO t(a) VALUES(?)")
    assert out == "INSERT INTO t(a) VALUES(%s) ON CONFLICT DO NOTHING"


def test_translate_autoincrement():
    out = pg.translate("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)")
    assert "AUTOINCREMENT" not in out
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out


def test_translate_leaves_plain_sql_unchanged():
    # No placeholders / rowid / quirks -> byte-identical (fast path).
    sql = "SELECT id, title FROM jobs WHERE match_score >= 50 ORDER BY date_found DESC"
    assert pg.translate(sql) == sql


# ----------------------------------------------------------------------------
# H3 — undefined COLUMN propagates; undefined TABLE degrades
# ----------------------------------------------------------------------------
@pytest.mark.asyncio
async def test_undefined_column_raises_not_swallowed(tmp_path):
    path = str(tmp_path / "h3.db")
    async with pg.connect(path) as db:
        await db.execute("CREATE TABLE h3t (id INTEGER PRIMARY KEY, name TEXT)")
        # A typo'd COLUMN must surface loudly — NOT be remapped to
        # OperationalError (which readers swallow with ``return []``).
        with pytest.raises(psycopg.errors.UndefinedColumn) as exc:
            await db.execute("SELECT no_such_col FROM h3t")
        # Proof it would escape ``except OperationalError: return []``.
        assert not isinstance(exc.value, pg.OperationalError)
    await pg.drop_schema(path)


@pytest.mark.asyncio
async def test_undefined_table_still_degrades_to_operationalerror(tmp_path):
    path = str(tmp_path / "h3tbl.db")
    async with pg.connect(path) as db:
        # A missing TABLE remains the graceful "feature not migrated yet" degrade.
        with pytest.raises(pg.OperationalError):
            await db.execute("SELECT * FROM totally_missing_table")
    await pg.drop_schema(path)


# ----------------------------------------------------------------------------
# V2 — lastrowid only probed when a row was inserted; SAVEPOINT-safe in a tx
# ----------------------------------------------------------------------------
@pytest.mark.asyncio
async def test_lastrowid_set_on_insert_none_on_ignored_conflict(tmp_path):
    path = str(tmp_path / "v2.db")
    async with pg.connect(path) as db:
        await db.execute(
            "CREATE TABLE v2t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE)"
        )
        cur = await db.execute("INSERT INTO v2t(name) VALUES(?)", ("alpha",))
        assert cur.lastrowid is not None  # real insert -> id available

        # INSERT OR IGNORE that CONFLICTS inserts nothing: lastrowid must be
        # None, not a STALE id from the previous insert (finding V2).
        cur2 = await db.execute("INSERT OR IGNORE INTO v2t(name) VALUES(?)", ("alpha",))
        assert cur2.lastrowid is None
    await pg.drop_schema(path)


@pytest.mark.asyncio
async def test_lastval_probe_is_savepoint_safe_inside_transaction(tmp_path):
    path = str(tmp_path / "v2tx.db")
    async with pg.connect(path) as db:
        # TEXT-PK table: an insert never touches a sequence, so lastval() errors.
        await db.execute("CREATE TABLE v2txt (id TEXT PRIMARY KEY, v TEXT)")
        # Inside a transaction the lastval() error must be isolated in a
        # SAVEPOINT so it can't poison the tx (this is exactly the migration
        # runner / _schema_migrations pattern, finding H2).
        async with db.transaction():
            cur = await db.execute("INSERT INTO v2txt(id, v) VALUES(?, ?)", ("k", "val"))
            assert cur.lastrowid is None  # no sequence -> None, and no poison
        # The INSERT survived the committed transaction.
        check = await db.execute("SELECT v FROM v2txt WHERE id = ?", ("k",))
        row = await check.fetchone()
        assert row is not None and row[0] == "val"
    await pg.drop_schema(path)


# --- SPLIT-P3: statement splitter must not sever $$ bodies / string literals ---


def test_split_statements_keeps_dollar_quoted_function_body_intact():
    """SPLIT-P3: a ';' inside a $$...$$ Postgres function body must NOT split.

    A naive `.split(';')` would sever this CREATE FUNCTION into 3 broken pieces,
    each an incomplete statement that errors at migration boot. The $$-aware
    splitter keeps the whole function as one statement.
    """
    script = """
    CREATE TABLE t (id int);
    CREATE FUNCTION bump() RETURNS trigger AS $$
    BEGIN
        NEW.updated_at := now();
        INSERT INTO audit(msg) VALUES ('changed; logged');
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    CREATE INDEX idx ON t (id);
    """
    stmts = pg.split_statements(script)
    assert len(stmts) == 3, f"expected 3 statements, got {len(stmts)}: {stmts}"
    body = stmts[1]
    assert body.startswith("CREATE FUNCTION")
    # the semicolons inside the body survived as one statement
    assert "NEW.updated_at := now();" in body
    assert "RETURN NEW;" in body
    assert "END;" in body
    assert body.rstrip().endswith("LANGUAGE plpgsql")


def test_split_statements_keeps_semicolon_inside_string_literal():
    """A ';' inside a '...' string literal must not split the statement."""
    script = "INSERT INTO t(msg) VALUES ('a; b; c'); SELECT 1;"
    stmts = pg.split_statements(script)
    assert len(stmts) == 2, f"expected 2, got {len(stmts)}: {stmts}"
    assert stmts[0] == "INSERT INTO t(msg) VALUES ('a; b; c')"
    assert stmts[1] == "SELECT 1"


def test_split_statements_normal_multi_statement_unchanged():
    """Ordinary multi-statement scripts still split exactly as before."""
    stmts = pg.split_statements("CREATE TABLE a(x int); CREATE TABLE b(y int);")
    assert stmts == ["CREATE TABLE a(x int)", "CREATE TABLE b(y int)"]
