import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Job360",
  description: "The terms for using Job360.",
};

// A legal document states when it changed; never derive this at render time.
const LAST_UPDATED = "5 September 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-semibold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: {LAST_UPDATED}
      </p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-medium text-foreground">
            1. The service
          </h2>
          <p className="mt-2">
            Job360 (job360.uk) stores the jobs you (or your own connected AI
            agent) bring in, keeps a full history of your applications —
            events, tailored documents, contacts, and receipts of what you
            sent — and can generate AI-tailored application documents. Your
            own AI agent (for example Claude or ChatGPT) can connect to your
            account and read or write this data on your behalf. By creating
            an account you agree to these terms and to our{" "}
            <a href="/privacy" className="underline">
              Privacy Policy
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            2. Your account
          </h2>
          <ul className="mt-2 list-disc space-y-2 pl-5">
            <li>You must provide a real email address you control.</li>
            <li>
              You are responsible for keeping your login credentials secure
              and for everything done under your account.
            </li>
            <li>
              You must only upload content you have the right to share (your
              own CV, your own LinkedIn export, your own GitHub username).
            </li>
            <li>One account per person; you must be 16 or older.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            3. Acceptable use
          </h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-2 pl-5">
            <li>
              scrape, harvest, or bulk-download the service or its job data;
            </li>
            <li>
              probe, disrupt, overload, or attempt to bypass security or
              usage limits;
            </li>
            <li>upload malicious files or unlawful content;</li>
            <li>
              resell or redistribute the service or its output as your own
              product.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            4. Job listings
          </h2>
          <p className="mt-2">
            Every job on Job360 is one you or your agent brought in yourself
            — by pasting the ad, or a link we fetch on your behalf. We do not
            search, rank, deduplicate, or score jobs, and we cannot guarantee
            that any listing you bring is accurate, current, or still open.
            Any fit assessment attached to an application is one you or your
            agent recorded yourselves — Job360 never judges or computes it.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            5. AI-generated documents
          </h2>
          <p className="mt-2">
            Tailored CVs and cover letters are drafts generated by AI from
            your own profile data. You must review them before sending them
            to anyone. You are responsible for their accuracy and for what
            you submit to employers — an AI draft that misstates your
            experience is still your application. Generated documents belong
            to you. Free accounts have a monthly generation limit, which is
            shown in the app.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            6. Availability and changes
          </h2>
          <p className="mt-2">
            The service is provided &ldquo;as is&rdquo; and &ldquo;as
            available&rdquo;. We may add, change, or remove features, and we
            may suspend accounts that break section 3. You can delete your
            account at any time from Settings, which erases your per-user
            data.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            7. Liability
          </h2>
          <p className="mt-2">
            To the fullest extent permitted by law, Job360 is not liable for
            indirect or consequential losses — including missed job
            opportunities, decisions made from a fit note you or your agent
            recorded, or the outcome of any application. Nothing in these
            terms limits liability that
            cannot be limited under the law of England and Wales, including
            for fraud. Our total liability for any claim is capped at the
            amount you paid us in the 12 months before the claim (zero for
            free accounts).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            8. Changes to these terms
          </h2>
          <p className="mt-2">
            If we make material changes, we post them here and update the
            date at the top. Continued use after that means you accept the
            updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            9. Governing law
          </h2>
          <p className="mt-2">
            These terms are governed by the law of England and Wales, and
            disputes belong to the courts of England and Wales. Questions:{" "}
            <a href="mailto:privacy@job360.uk" className="underline">
              privacy@job360.uk
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
