"""Write the countable facts INTO the docs from code. Generation, not detection.

The doc-truth loop spent seventeen nightly runs detecting drift, and grew 26
guards and ~2,260 lines of checker to do it. Every one of those guards watches
a fact that is DERIVABLE: the registry size, the rate-limit count, the
migration head, how many entries LOCATIONS holds. A guard makes drift VISIBLE.
A generator makes it IMPOSSIBLE -- and costs nothing to maintain afterwards,
because there is no second copy to keep in step.

That is the difference between a smoke alarm and not keeping petrol in the
hallway. This file is the second thing.

HOW IT WORKS
    A doc marks a region:

        <!-- generated: code-facts -->
        ...anything here is overwritten...
        <!-- /generated -->

    `python scripts/gen_doc_blocks.py --write` fills every marked region from
    the code. `--check` (what CI runs) regenerates in memory and fails if the
    file on disk differs, so a stale block cannot survive a push.

WHY --check RATHER THAN JUST TRUSTING --write
    Nobody remembers to run a generator. The check is the enforcement; the
    writer is the convenience. This mirrors gen-api-types.sh, which the gate
    already runs the same way.

ADDING A FACT
    Add a producer to BLOCKS. Prefer deleting the hand-written sentence that
    stated the same fact -- a generated block beside a prose restatement is two
    copies again, which is the problem this file exists to end.
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def _checker():
    """The extractors already live in doc_sync_check.py — reuse, do not re-derive.

    Two extractors for one fact is exactly the duplication being removed. If
    they ever disagreed, the guard and the generated text would fight forever.
    """
    spec = importlib.util.spec_from_file_location(
        "doc_sync_check", ROOT / "scripts" / "doc_sync_check.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def code_facts() -> str:
    c = _checker()
    registry, unique = c.registry_counts()
    slugs, platforms = c.ats_slug_count()
    rows = [
        "| Fact | Value | Where the code says it |",
        "| --- | --- | --- |",
        f"| `SOURCE_REGISTRY` keys | **{registry}** | `src/main.py` `SOURCE_REGISTRY` |",
        f"| Unique source classes | **{unique}** | same dict — `indeed` and `glassdoor` both alias `JobSpySource` |",
        f"| `RATE_LIMITS` entries | **{c.rate_limit_count()}** | `core/settings.py` `RATE_LIMITS` |",
        f"| `LOCATIONS` entries | **{c.locations_count()}** | `core/keywords.py` `LOCATIONS` |",
        f"| Migration head | **{c.migration_head():04d}** | `backend/migrations/` |",
        f"| `SCORER_VERSION` | **{c.scorer_version()}** | `services/skill_matcher.SCORER_VERSION` |",
        f"| `BaseJobSource` subclasses | **{c.source_subclass_count()}** | `src/sources/` |",
        f"| ATS board slugs | **{slugs}** across **{platforms}** platforms | `src/data/` ATS slug files |",
        f"| Enrichment enum values | **{c.enrichment_enum_count()}** | `services/enrichment` schema |",
        f"| Migration files | **{c.migration_file_count()}** | `backend/migrations/*.up.sql` |",
        f"| `test_*.py` files | **{c.test_file_count()}** | `backend/tests/` |",
        f"| GitHub Actions workflows | **{c.workflow_count()}** | `.github/workflows/` |",
        f"| Hard rules in CLAUDE.md | **{c.hard_rule_count()}** | root `CLAUDE.md` |",
    ]
    return "\n".join(rows)


# doc -> {block name: producer}
BLOCKS: dict[str, dict[str, callable]] = {
    "ARCHITECTURE.md": {"code-facts": code_facts},
}

OPEN = "<!-- generated: {name} -->"
CLOSE = "<!-- /generated -->"


def _render(text: str, name: str, body: str) -> tuple[str, bool]:
    open_tag = OPEN.format(name=name)
    pat = re.compile(
        re.escape(open_tag) + r".*?" + re.escape(CLOSE), re.S)
    if not pat.search(text):
        return text, False
    new = f"{open_tag}\n<!-- Generated by scripts/gen_doc_blocks.py — do not edit by hand. -->\n\n{body}\n{CLOSE}"
    return pat.sub(lambda _: new, text, count=1), True


def main() -> int:
    write = "--write" in sys.argv
    stale: list[str] = []
    missing: list[str] = []

    for rel, blocks in BLOCKS.items():
        path = ROOT / rel
        if not path.exists():
            missing.append(f"{rel}: file not found")
            continue
        original = path.read_text(encoding="utf-8", errors="replace")
        text = original
        for name, produce in blocks.items():
            text, found = _render(text, name, produce())
            if not found:
                # Loud, not silent: a generator whose marker vanished is a
                # block that has quietly gone back to being hand-written.
                missing.append(f"{rel}: no '{name}' block — marker deleted?")
        if text != original:
            if write:
                path.write_text(text, encoding="utf-8")
                print(f"wrote {rel}")
            else:
                stale.append(rel)

    if missing:
        print("MISSING MARKERS")
        for m in missing:
            print(f"  {m}")
    if stale:
        print("STALE GENERATED BLOCKS — run: python scripts/gen_doc_blocks.py --write")
        for s in stale:
            print(f"  {s}")
    if missing or stale:
        return 1
    print("generated doc blocks are current" if not write else "done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
