/**
 * The full ISO-3166-1 alpha-2 code list, for the "Countries where I can
 * already work" picker (docs/product/VISION.md decision 27 — a country
 * picker is UX sugar only; the backend's `_countries_or_422` /
 * `normalize_country_codes` validate any alpha-2 shape and store the code,
 * never a name Job360 interprets).
 *
 * `Intl.supportedValuesOf` (ECMA-402) does NOT enumerate regions — it only
 * covers calendar/collation/currency/numberingSystem/timeZone/unit, so there
 * is no runtime call that hands back "every country code". This is the
 * complete, standard ISO-3166-1 alpha-2 set (not a hand-picked partial
 * list — every officially assigned code, including small territories), used
 * only as the finite INPUT to `Intl.DisplayNames`, which is what actually
 * generates the English name shown to the user. Nothing here is a country
 * NAME typed by hand.
 */
const ISO_3166_1_ALPHA_2: readonly string[] = [
  "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ",
  "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BY", "BZ",
  "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ",
  "DE", "DJ", "DK", "DM", "DO", "DZ",
  "EC", "EE", "EG", "EH", "ER", "ES", "ET",
  "FI", "FJ", "FK", "FM", "FO", "FR",
  "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY",
  "HK", "HM", "HN", "HR", "HT", "HU",
  "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT",
  "JE", "JM", "JO", "JP",
  "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ",
  "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY",
  "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ",
  "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ",
  "OM",
  "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY",
  "QA",
  "RE", "RO", "RS", "RU", "RW",
  "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ",
  "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW", "TZ",
  "UA", "UG", "UM", "US", "UY", "UZ",
  "VA", "VC", "VE", "VG", "VI", "VN", "VU",
  "WF", "WS",
  "YE", "YT",
  "ZA", "ZM", "ZW",
];

export interface Country {
  code: string;
  name: string;
}

let cached: Country[] | null = null;

/** Every ISO alpha-2 code above, with its English display name generated by
 * `Intl.DisplayNames`, sorted by name. A code the runtime can't resolve a
 * name for (very old engines) falls back to showing the bare code rather
 * than throwing or vanishing from the list. */
export function allCountries(): Country[] {
  if (cached) return cached;
  let names: Intl.DisplayNames | null = null;
  try {
    names = new Intl.DisplayNames(["en"], { type: "region" });
  } catch {
    names = null;
  }
  cached = ISO_3166_1_ALPHA_2.map((code) => {
    let name = code;
    try {
      name = names?.of(code) || code;
    } catch {
      name = code;
    }
    return { code, name };
  }).sort((a, b) => a.name.localeCompare(b.name));
  return cached;
}

/** The display name for a stored ISO code — the code itself if the runtime
 * cannot resolve it, so an old or unusual value never renders as blank. */
export function countryName(code: string): string {
  const found = allCountries().find((c) => c.code === code);
  return found ? found.name : code;
}
